# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-28 11:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0004_auto_20171027_1344'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subscribe_model',
            old_name='sub',
            new_name='post',
        ),
    ]
