# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-28 11:33
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contact', '0005_auto_20171028_1112'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscribe_model',
            name='user',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='subscribe_model',
            name='post',
            field=models.EmailField(default='', max_length=254),
        ),
    ]
