# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-29 09:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0010_auto_20171028_1742'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='user',
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='description',
            field=models.TextField(),
        ),
    ]
